name: Build & Publish Docker IMage

on: 
    release:
        types: [published]
    


jobs: 
    push-to-dockerhub: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USSER}}
                    password: ${{ secrets.DOCKER_PASSWROD}}
            - name: Log in to GHCR 
              uses: docker/login-action@v2
              with:
                    registry: ghcr.io
                    username: ${{ github.actor}}
                    password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract Metadata
              id: metadata
              uses: docker/metadata-action@v4
              with:
                images: alialaa17/simple-node-api
                tags: |
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
            - name: Build & Publish Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }}



